[build]
publish = "public"
command = "npm run build"
functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
  
[[redirects]]
  from = "/2022-ffdw-report/"
  to = "/blog/2022-ffdw-report/"
  status = 200
  force = true

